# Site Configuration
title: "Security Labs Documentation"
description: "Technical documentation of 60+ hands-on security laboratories"
url: "https://issamentacode.github.io"
baseurl: "/labs"
remote_theme: just-the-docs/just-the-docs

# Search
search_enabled: true

# Navigation
heading_anchors: true

# Footer
footer_content: >
  © 2026 Issa MENTA | Cybersecurity Engineer

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - assets
